name: CI Build, Test, Scan and Push
#asdsdsASDsasd
on:
    push:
        branches:
            - main
        paths:
            - 'app/**'
            - '.github/workflows/ci.yaml'

    pull_request:
        branches:
            - main
        paths:
            - 'app/**'
            - '.github/workflows/ci.yaml'

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
  lint:
    uses: ./.github/workflows/linter.yml

  sast:
    uses: ./.github/workflows/codescans.yml
    secrets:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

  ecrpush:
    needs: [lint, sast]
    uses: ./.github/workflows/buildscanpush.yml
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}

  pushtotest:
    needs: ecrpush
    if: ${{ github.event_name == 'pull' || github.event_name == 'push' }} && github.event.action == 'closed'
    uses: ./.github/workflows/pushtotest.yml
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}

    
  dastscan:
    needs: pushtotest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: alb_dns_artifact
          path: .
      
      - name: echo variable
        run: |
          alb_dns=$(cat alb_dns.txt)
          echo "alb_dns=$alb_dns" >> $GITHUB_OUTPUT

      
    
    

