name: CI Build, Test, Scan and Push
#test
on:
    push:
        branches:
            - main
        paths:
            - 'app/**'
            - '.github/workflows/ci.yaml'

    pull_request:
        branches:
            - main
        paths:
            - 'app/**'
            - '.github/workflows/ci.yaml'

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
  lint:
    uses: ./.github/workflows/linter.yml

  sast:
    uses: ./.github/workflows/codescans.yml
    secrets:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

  ecrpush:
    needs: [lint, sast]
    uses: ./.github/workflows/buildscanpush.yml
    if: ${{ github.event_name == 'pull' || github.event_name == 'push' }} && github.event.action == 'closed'
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}

