name: deploy to test/prod

on:
    workflow_dispatch:

            

jobs:
    testjob:
        environment:
            production
        runs-on: ubuntu-latest
        steps:
            - name: helloworld
              run: echo "helloworld"
