name: deploy to prod

on:
    workflow_call:
        secrets:
            AWS_ACCESS_KEY_ID:
                required: true
            AWS_SECRET_ACCESS_KEY:
                required: true
            AWS_REGION:
                required: true
            
            

jobs:
    testdeploy:
        environment:
            test
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: terraform/environments/test
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Configure AWS Creds
              uses: aws-actions/configure-aws-credentials@v4
              with:
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                aws-region: ${{ secrets.AWS_REGION }}

            - name: Setup TF
              uses: hashicorp/setup-terraform@v3

            - name: Format TF code
              run: terraform fmt

            - name: Initialise TF
              run: terraform init 

            - name: Validate TF code
              run: terraform validate
              
            - name: Plan terraform
              run: terraform plan 

